# Generated by Django 5.1.1 on 2024-11-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Play_rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('play_id', models.CharField(max_length=300)),
                ('play_name', models.CharField(max_length=300)),
                ('play_period', models.CharField(max_length=300)),
                ('theater_nm', models.CharField(max_length=300)),
                ('rank_area', models.CharField(max_length=50)),
                ('play_poster', models.CharField(max_length=300)),
                ('ststypes', models.CharField(max_length=50)),
                ('link_area', models.CharField(max_length=50)),
                ('rank_reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Play_rank',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('star_total', models.DecimalField(decimal_places=1, max_digits=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Star',
            },
        ),
        migrations.CreateModel(
            name='Theater_location',
            fields=[
                ('mt10id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('theater_nm', models.CharField(max_length=300)),
                ('addr', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Theater_location',
            },
        ),
        migrations.CreateModel(
            name='Play_list',
            fields=[
                ('play_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('play_name', models.CharField(max_length=300)),
                ('play_reg_date', models.DateTimeField()),
                ('genre', models.CharField(blank=True, max_length=300, null=True)),
                ('dislike_users', models.ManyToManyField(blank=True, related_name='disliked_plays', to=settings.AUTH_USER_MODEL)),
                ('favorite_users', models.ManyToManyField(blank=True, related_name='favorited_plays', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(blank=True, related_name='liked_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Play_list',
            },
        ),
        migrations.CreateModel(
            name='Play_detail',
            fields=[
                ('playdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_name', models.CharField(max_length=300)),
                ('genre', models.CharField(blank=True, max_length=300, null=True)),
                ('play_strdate', models.CharField(max_length=300)),
                ('play_enddate', models.CharField(max_length=300)),
                ('theater_nm', models.CharField(max_length=300)),
                ('play_forcast', models.CharField(max_length=300, null=True)),
                ('play_runtime', models.CharField(max_length=50, null=True)),
                ('play_age', models.CharField(max_length=50, null=True)),
                ('play_guidance', models.CharField(max_length=300, null=True)),
                ('play_poster', models.CharField(max_length=300, null=True)),
                ('loc', models.CharField(max_length=300)),
                ('play_status', models.CharField(max_length=50)),
                ('styurls_1', models.CharField(blank=True, max_length=300, null=True)),
                ('styurls_2', models.CharField(blank=True, max_length=300, null=True)),
                ('styurls_3', models.CharField(blank=True, max_length=300, null=True)),
                ('styurls_4', models.CharField(blank=True, max_length=300, null=True)),
                ('dtguidance', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_1', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_1', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_2', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_2', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_3', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_3', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_4', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_4', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_5', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_5', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_6', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_6', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_7', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_7', models.CharField(blank=True, max_length=300, null=True)),
                ('relate_8', models.CharField(blank=True, max_length=300, null=True)),
                ('relateurl_8', models.CharField(blank=True, max_length=300, null=True)),
                ('play_id', models.OneToOneField(db_column='play_id', on_delete=django.db.models.deletion.CASCADE, to='common.play_list')),
                ('mt10id', models.ForeignKey(db_column='mt10id', on_delete=django.db.models.deletion.CASCADE, to='common.theater_location')),
            ],
            options={
                'db_table': 'Play_detail',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_name', models.CharField(max_length=300)),
                ('theater_nm', models.CharField(max_length=300)),
                ('loc', models.CharField(max_length=300)),
                ('review_title', models.CharField(max_length=255)),
                ('review_contents', models.CharField(max_length=1000)),
                ('review_reg_date', models.DateTimeField(auto_now_add=True)),
                ('dislike_users', models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('play_id', models.ForeignKey(db_column='play_id', on_delete=django.db.models.deletion.CASCADE, to='common.play_detail')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('star', models.ForeignKey(db_column='star', on_delete=django.db.models.deletion.CASCADE, to='common.star')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
